"""Build the index page for the test reports published to GitHub Pages.

Usage: python build_report_index.py <site_dir>

Reads the run details from environment variables set by the workflow, and links to
whichever report files are present in <site_dir>.
"""

import html
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

REPORTS = [
    ("UI tests", "ui-report.html", "UI_RESULT"),
    ("API tests", "api-report.html", "API_RESULT"),
]

STATUS = {
    "success": ("Passed", "pass"),
    "failure": ("Failed", "fail"),
    "cancelled": ("Cancelled", "other"),
    "skipped": ("Skipped", "other"),
}

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>python-test-app test reports</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 640px; margin: 40px auto; padding: 0 16px;
         color: #1f2328; background: #fff; }}
  h1 {{ font-size: 1.5rem; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ display: flex; justify-content: space-between; align-items: center; padding: 12px 16px;
        border: 1px solid #d1d9e0; border-radius: 6px; margin-bottom: 8px; }}
  .badge {{ font-size: 0.85rem; font-weight: 600; padding: 2px 10px; border-radius: 12px; }}
  .pass {{ background: #dafbe1; color: #1a7f37; }}
  .fail {{ background: #ffebe9; color: #cf222e; }}
  .other {{ background: #eff2f5; color: #59636e; }}
  .meta {{ color: #59636e; font-size: 0.9rem; line-height: 1.6; }}
  a {{ color: #0969da; }}
</style>
</head>
<body>
<h1>Test reports</h1>
<p class="meta">Latest run on <code>main</code> of
  <a href="{repo_url}">{repo}</a><br>
  Run <a href="{run_url}">#{run_number}</a> &middot; commit
  <a href="{commit_url}"><code>{short_sha}</code></a> &middot; {generated}</p>
<ul>
{items}
</ul>
<p class="meta">Reports are generated by pytest-html. Failed tests include the error and
traceback; the fallback's "Chrome dropped" warnings appear in each UI test's captured log.</p>
</body>
</html>
"""


def build(site_dir: Path) -> str:
    repo = os.environ.get("GITHUB_REPOSITORY", "dustyspinster/python-test-app")
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    sha = os.environ.get("GITHUB_SHA", "")
    run_id = os.environ.get("GITHUB_RUN_ID", "")

    items = []
    for label, filename, result_var in REPORTS:
        text, css = STATUS.get(os.environ.get(result_var, ""), ("Unknown", "other"))
        if (site_dir / filename).exists():
            name = f'<a href="{filename}">{label}</a>'
        else:
            name = f"{label} <span class='meta'>(no report)</span>"
        items.append(f'  <li>{name}<span class="badge {css}">{text}</span></li>')

    return PAGE.format(
        repo=html.escape(repo),
        repo_url=f"{server}/{repo}",
        run_url=f"{server}/{repo}/actions/runs/{run_id}",
        run_number=html.escape(os.environ.get("GITHUB_RUN_NUMBER", "?")),
        commit_url=f"{server}/{repo}/commit/{sha}",
        short_sha=html.escape(sha[:7]),
        generated=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
        items="\n".join(items),
    )


if __name__ == "__main__":
    site = Path(sys.argv[1])
    site.mkdir(parents=True, exist_ok=True)
    (site / "index.html").write_text(build(site), encoding="utf-8")
    print(f"Wrote {site / 'index.html'}")
